version: '3.8'

services:
  signature-portal:
    build: .
    container_name: wpweb_signature_portal
    # Mapeia a porta 8080 da VPS para a porta 80 do Nginx dentro do container
    ports:
      - "8080:80"
    # Garante que o site suba sozinho se a VPS for reiniciada
    restart: always
    # Opcional: Define limites de memória para não travar a VPS
    deploy:
      resources:
        limits:
          memory: 256M