name: Deploy Portal WP Web

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v3

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build do Projeto Web
        run: |
          flutter pub get
          flutter build web --release --web-renderer canvaskit

      # PASSO VITAL: Ele envia a pasta build/web que o GitHub acabou de criar
      - name: Enviar arquivos para a VPS via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "build/web,Dockerfile,docker-compose.yml"
          target: "/home/ubuntu/WPWebSolucoes-signature"
          strip_components: 0

      # PASSO FINAL: Avisa a VPS para atualizar o container
      - name: Restart do Docker na VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/WPWebSolucoes-signature
            docker compose up -d --build
            docker image prune -f