name: Deploy Portal WP Web

on:
  push:
    branches: [ main ] # Dispara o deploy quando houver push na main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Executar Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # 1. Entra na pasta correta
            cd /home/ubuntu/WPWebSolucoes-signature

            # 2. Puxa a versão mais nova do GitHub
            git pull origin main

            # 3. Reconstrói o container Docker
            docker compose up -d --build

            # 4. Limpa lixo de imagens antigas para economizar espaço na VPS
            docker image prune -f