name: Deploy Portal WP Web

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build do Projeto Web
        run: |
          flutter config --enable-web
          flutter pub get
          # O segredo está na palavra 'web' logo após o 'build'
          flutter build web --release --web-renderer canvaskit

      - name: Enviar para a VPS (SCP)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          # Enviamos a pasta build/web, o Dockerfile e o docker-compose
          source: "build/web,Dockerfile,docker-compose.yml"
          target: "/home/ubuntu/WPWebSolucoes-signature"
          strip_components: 0

      - name: Restart do Docker na VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/WPWebSolucoes-signature
            docker compose up -d --build
            docker image prune -f