name: Deploy Portal (Envio de Build Pronto)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Enviar Build e Docker via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          # Aqui ele envia a pasta que você buildou no PC e subiu no Git
          source: "build/web,Dockerfile,docker-compose.yml"
          target: "/home/ubuntu/WPWebSolucoes-signature"
          strip_components: 0

      - name: Restart do Docker na VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/WPWebSolucoes-signature
            docker compose up -d --build
            docker image prune -f