- name: Executar Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # Entra na pasta do usuário ubuntu
            cd /home/ubuntu/WPWebSolucoes-signature 

            # Puxa o código novo
            git pull origin main

            # Sobe o Docker
            docker compose up -d --build
            docker image prune -f